name: density-maps
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip 
  - pip:
    - geopandas
    - matplotlib
    - numpy
    - pandas
    - pyproj
    - rasterio
    - requests
    - shapely
    - xarray
    - xarray-spatial
    - streamlit
    - datashader
    - duckdb